apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: star-wars-translations
  description: API to get star wars translations
spec:
  type: openapi
  lifecycle: experimental
  owner: marks-team
  definition: ./open-api.yaml
