apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My test api
spec:
  type: openapi
  lifecycle: experimental
  owner: marks-team
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Marks API
    servers:
      - url: http://marks.api.com
    paths:
      /marks:
        get:
          summary: Get all Marks
