apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-api
  description: My test api
spec:
  type: openapi
  lifecycle: experimental
  owner: marks-team
  definition: 
    $yaml: https://github.com/limptwiglet/open-api-test/blob/main/open-api.yaml
