apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api2
  description: My API2
spec:
  type: openapi
  lifecycle: experimental
  owner: team2
  definition: |
    openapi: 3.0.0
    info:
      version: 1.0.1
      title: API2
    servers:
      - url: http://api2.api.com
    paths:
      /api1:
        get:
          summary: Get all Marks
        post:
          summary: Create a Mark
      /api1/{id}:
        get:
          summary: Get a Person
