openapi: 3.0.0
info:
  version: 1.0.1
  title: API3
servers:
  - url: http://api1.api.com
paths:
  /api1:
    get:
      summary: Get all Marks
    post:
      summary: Create a Mark
  /api1/{id}:
    get:
      summary: Get a Person